### ISSUE TITLE
Enhanced Economy - the side keys of the mouse do not work

### ISSUE THREAD

**Issue by blockhead999** [llde/xOBSE#101]
resets the side key (or mouse keys) when assigning it to the "activate" action in the ini - "Activate=003903FF" - after the dialog with the npc-
at 21.4, the key roll back
Of course I may be mistaken,as have not tested this in vanilla version because I play in a huge plugins Assembly OAssociation 0.9.3. and maybe there are some mods for the processing dialogs (but not yet found,though sought)
not that I can't play by clicking on the "space bar" but for the convenience of collecting the ingredients
again, if the vanilla version doesn't have this, then you don't have to try to edit it.
Well, I will try to find a mod from this build for any change to the dialogs, if there is one at all))

**Comment by blockhead999** [comment]
I understand that this topic may be incorrect because the build has quite a lot of plugins that reassign keys..and the problem may not lie in one plugin for "Dialogs".So it is better if someone would test it on vanilla or I can throw off the list of plugins..for the definition of such an erroneous plugin if at all in the end it is the case

**Comment by llde** [comment]
I'm not actually understanding the issue reported.You setted the activate control  to a  mouse key and then the association is reverted to the previous key? 
And this doesn't happen with OBSE 21?
In case can you check if xOBSE 22.1 already experience this problem?

**Comment by blockhead999** [comment]
I tested the button on vanilla steam and also on the build, after disabling all additional mods and plugins except for dls.

result:the button works after the dialog on 22.3.1

so it's all about some plugin

and in this assembly there are about 100 of them))0
[Plugins.txt](https://github.com/llde/xOBSE/files/6651618/Plugins.txt)


I mayby will try to calculate the plugin or mod and write here later or not.

**Comment by blockhead999** [comment]
I calculated this plugin out of 170 through tests))0
this plugin https://www.nexusmods.com/oblivion/mods/25078
and it was 5.4.3 that was used in the build.It was because of him that the Activate=003903FF key was reset on 22.3.1

I also tested it by disabling everything except this mod and dls.

**Comment by llde** [comment]
@blockhead999 OK It tested, and look Enhanced Economy use the input commands in a completly wrong way. Literally it has a  quite of totally incorrect stuff it's doing (using 0 as no key ,when 0 is a valid key scan code for example)
 This effect didn't manifest becouse of a bug in the old OBSE regarding mouse controls. 

I will try to make a mitigation for this specific issue, but I'm considering on making this a "wontfix"

**Comment by blockhead999** [comment]
thanks for your work! :)
