### ISSUE TITLE
checksum not found

### ISSUE THREAD

**Issue by MomidiMomidi** [llde/xOBSE#106]
I bought it at GOG.
I'm using the unofficial Japanese patch version v15.
Please add a CRC.
Oblivion Version 1.2.0.416
crc = 2D73D2FF

**Comment by llde** [comment]
case 0x3DBB32D1:	// 1.2.0.416 japanese unofficial v15
      case 0x7CD1332D:	// 1.2.0.416 japanese unofficial v15 (proper PE checksum)
Strange the CRCs for jap unofficial v15 is already included. 
Is this a newer version of the executable patch?
What are the changes backed into the executable?

**Comment by MomidiMomidi** [comment]
Two of them are for DVD.
The one I presented is for GOG.
There are no other changes.

**Comment by llde** [comment]
GOG version CRC is already included. So where this executable came from?

**Comment by MomidiMomidi** [comment]
This is a patch applied to translate the GOG executable file into Japanese.
When I patch Oblivion.exe, the CRC changes, so I get "checksum not found".

**Comment by llde** [comment]
Yes I'm asking where this patch came from

**Comment by MomidiMomidi** [comment]
The source is
https://egg.5ch.net/test/read.cgi/game/1570671341/673

I can imagine that the changes are not written, but I think that it is the same as the DVD version.
If it's the whole change from the original executable
https://jpmod.oblivion.z49.org/?%E6%97%A5%E6%9C%AC%E8%AA%9E%E5%8C%96%E3%83%91%E3%83%83% E3% 83% 81
It is written here.

**Comment by llde** [comment]
ok thanks.

**Comment by llde** [comment]
@MomidiMomidi You can use the loader from https://ci.appveyor.com/project/llde/xobse/builds/40031327/job/jhe32rsibdmdstm3 when it end compiling

**Comment by MomidiMomidi** [comment]
@llde 
It seems to be working properly.
Thank you.
