### ISSUE TITLE
Double-Tab Dodge

### ISSUE THREAD

**Issue by EtaYorius** [llde/xOBSE#111]
I think the latest version completely broke Oblivion "Double Tap Dodge" mod, since as soon as you move in any direction the player character will start dodging all over the place without actually doing the double tap that triggers the dodge.

Here is the mod, just in case author wants to take a look and possibly fix it:

https://www.nexusmods.com/oblivion/mods/35727?tab=posts&BH=0

The mod is rather old, not sure if just bad old code from Double-Tap Dodge or if it's actually xOBSE the one at fault.

**Comment by llde** [comment]
thanks I will check

**Comment by EtaYorius** [comment]
I only tested for a couple minutes but my character stopped dodging all over the place, so it seems to have worked. Thanks!
