### ISSUE TITLE
Latest version doesn't work anymore

### ISSUE THREAD

**Issue by PrinceJaxonHellsing** [llde/xOBSE#112]
I've been trying to use OBSE and it won't load with steam, I've tried a version that should work but when I load into the menu it says it can't be detected. PLEASE FIX THIS!

**Comment by llde** [comment]
If Steam doesn't load even if the onse_Steam_loader.dll is in the Oblivion directory, try starting with the obse_loader.exe

**Comment by PrinceJaxonHellsing** [comment]
I've tried using it separately but it doesn't detect my mods or anything

**Comment by PrinceJaxonHellsing** [comment]
but it loads the launcher instead of the game

**Comment by PrinceJaxonHellsing** [comment]
or if I had the working version, even opening it through the folder doesn't work

**Comment by llde** [comment]
What if you try the laucnher when the OblivionLauncher and steam are already open?

**Comment by PrinceJaxonHellsing** [comment]
nope. I tried just now, even with it open through steam then launching obse with both open doesn't work.

**Comment by PrinceJaxonHellsing** [comment]
ahh didn't mean to close

**Comment by llde** [comment]
Ok last try:
rename obse_loader.exe to OblivionLauncher.exe and start the game with steam (rename obse_steam_loader.dll to something else to prevent fuckery if steam decide suddenly to load it)

**Comment by PrinceJaxonHellsing** [comment]
it works, but it doesn't detect obse

**Comment by llde** [comment]
send the obse.log

**Comment by PrinceJaxonHellsing** [comment]
I've never sent anything on here before. how do I do it? sorry for all the trouble btw

**Comment by llde** [comment]
drag and drop

**Comment by PrinceJaxonHellsing** [comment]
[obse.log](https://github.com/llde/xOBSE/files/6911209/obse.log)

**Comment by llde** [comment]
obse_loader.log?

**Comment by PrinceJaxonHellsing** [comment]
woops wrong one XD here. 
[obse_loader.log](https://github.com/llde/xOBSE/files/6911216/obse_loader.log)

**Comment by PrinceJaxonHellsing** [comment]
I do have steam overlay on though

**Comment by llde** [comment]
what version you are using? the log imply an older version of OBSE

**Comment by PrinceJaxonHellsing** [comment]
weird. I'm using 0021. but I didn't see any other versions that are higher

**Comment by llde** [comment]
This one should report 22.3

**Comment by PrinceJaxonHellsing** [comment]
is there a 22.3 on the page? I never saw it

**Comment by llde** [comment]
Release Tab

**Comment by PrinceJaxonHellsing** [comment]
I oddly don't see that release on silverlock but I looked it up instead and found it. thanks for helping me

**Comment by llde** [comment]
Silverlock just link to this github, don't point the precise releases

**Comment by PrinceJaxonHellsing** [comment]
I have returned to find obse 22.3.1 isn't working now, it doesn't give me any errors what so ever, but when I launch the game it crashes, I've tried disabling all of my mods, that doesn't work. I've tried doing a fresh install, that didn't work. I've tried deleting oblivion.ini and the oblivion folder itself in documents/mygames that does nothing. idk why this is happening.
