### ISSUE TITLE
Obse crashes with latest version

### ISSUE THREAD

**Issue by PrinceJaxonHellsing** [llde/xOBSE#114]
I have returned to find obse 22.3.1 isn't working now, it doesn't give me any errors what so ever, but when I launch the game it crashes, I've tried disabling all of my mods, that doesn't work. I've tried doing a fresh install, that didn't work. I've tried deleting oblivion.ini and the oblivion folder itself in documents/mygames that does nothing. idk why this is happening.

**Comment by llde** [comment]
after launching the game, send me obse.log and obse_launncher.log. And also MEssageLog.txt and CobbCrashLogger (first one is from MEssageLogger and second from Cobb's Crash Logger)

**Comment by PrinceJaxonHellsing** [comment]
[obse.log](https://github.com/llde/xOBSE/files/6919917/obse.log)
[obse_loader.log](https://github.com/llde/xOBSE/files/6919920/obse_loader.log)
these 2?

**Comment by llde** [comment]
install Cobb crash logger and MEssage Log, and send me the result of these 2

**Comment by PrinceJaxonHellsing** [comment]
[obse.log](https://github.com/llde/xOBSE/files/6920193/obse.log)
[obse_loader.log](https://github.com/llde/xOBSE/files/6920194/obse_loader.log)
unsure if it worked but I did install those plugins

**Comment by llde** [comment]
You need to give me the log files of these 2 plugins

**Comment by PrinceJaxonHellsing** [comment]
here
[CobbCrashLogger.log](https://github.com/llde/xOBSE/files/6927303/CobbCrashLogger.log)
[MessageLog.txt](https://github.com/llde/xOBSE/files/6927313/MessageLog.txt)
[obse_loader.log](https://github.com/llde/xOBSE/files/6927314/obse_loader.log)

**Comment by llde** [comment]
2021/08/03 18:12:36  [00574A68] [WARNING]   Font file not found: Data\Fonts\DarN_Kingthings_Petrock_14.fnt. 

2021/08/03 18:12:36  [00574A68] [WARNING]   Font file not found: Data\Fonts\DarN_Kingthings_Petrock_16.fnt. 

2021/08/03 18:12:36  [00574A68] [WARNING]   Font file not found: Data\Fonts\DarN_Oblivion_28.fnt. 

2021/08/03 18:12:36  [00574A68] [WARNING]   Font file not found: Data\Fonts\Handwritten.fnt. 

You have DarnUI fonts setted in the ùOblivion.ini but the fonts aren't found in the game directory.
If the file aren't in that position reinstall DarnUI (or fork) and retry. If they are actually in that position report back.

**Comment by PrinceJaxonHellsing** [comment]
I'm back. I managed to get the txt files but it still won't load. The only time it loads is when I delete the entire oblivion folder in documents. this is all my message logger says now. 
[MessageLog.txt](https://github.com/llde/xOBSE/files/6989145/MessageLog.txt)

**Comment by llde** [comment]
Bad INI settings then
