### ISSUE TITLE
New version crashes within a few minutes of playing/fast travelling

### ISSUE THREAD

**Issue by TheLaziestGamer** [llde/xOBSE#115]
Newer version keeps crashing, should I go back to the previous version?

[obse.log](https://github.com/llde/xOBSE/files/6964939/obse.log)
[obse_loader.log](https://github.com/llde/xOBSE/files/6964940/obse_loader.log)
[CobbCrashLogger.log](https://github.com/llde/xOBSE/files/6964941/CobbCrashLogger.log)
[MessageLog.txt](https://github.com/llde/xOBSE/files/6964942/MessageLog.txt)

**Comment by llde** [comment]
the previous version had no such issue?

**Comment by llde** [comment]
Can you backtrack the versions to check which version introduced the issue?

**Comment by TheLaziestGamer** [comment]
> Can you backtrack the versions to check which version introduced the issue?

I've only ever used 2 version of xOBSE (I don't use regular OBSE, as a plugin called Supreme Magicka requires xOBSE and not regular OBSE) the previous 22.3.1 and the latest one, 22.4.1 . I updated to the latest one from the previous one and I've gotten a lot of crashes. Reverted back to 22.3.1, still had crashes

**Comment by llde** [comment]
Can you try using the older OBSE for once to check if the issue was introduced with xOBSE? Unfortunatly the Crash Logger contains no info  (can happen when the heap is corrupted).
Temporary disable Supreme Magicka if necessary.

 But honestly I feel like xOBSE isn't responsible at all. Responsibility may lies in one of the plugins (OSR settings for example) or one of your mods (the MessageLogger is complaining a lot)

**Comment by llde** [comment]
The overall method is to bisect: removing half mods, test, if still happen removing half of the remaining mods, if doesn't happen anymore reenable half of the ods you disabled, repeat from test

**Comment by TheLaziestGamer** [comment]
Reinstalled Oblivion by buying it on steam. Got the GOTY Deluxe with only $3. Cut a few mods from my old mod list and it runs beautiful, no crashes. Maybe it's because I used a crack or whatever, it's still unclear. But all is well, thanks for helping me a bit
