### ISSUE TITLE
Functions to set camera FOV do not function as expected

### ISSUE THREAD

**Issue by katawful** [llde/xOBSE#117]
There are 2 ways to set the FOV by script in Oblivion: `con_SetCameraFOV` and `SetNumericINISetting "fDefaultFOV:Display"`. Neither work as expected.

`con_SetCameraFOV`: This function sets the FOV to (almost) any setting supplied by the user that fits within Oblivion's camera projection. You can adjust it above and below. However, for some reason, Bethesda clamped the maximum value in code to 160 instead of 180. While not particularly useful above 160 degrees, it might pose issue for some use cases (32:9 displays come to mind). Being that this is a vanilla feature, patching this might be out of the scope of xOBSE

`SetNumericINISetting`: This function sets the FOV to any value, only if it is above the current FOV set by this function. In order to go lower, you must use the other console based FOV function. Lower values achieve nothing. This makes FOV modifier mods much more complex than they need to be. Either they clamp max value to 160, experience weird behavior above 160, or have to build a system to watch for a decrease in FOV and set FOV with the console function

At the least, these problems should be noted within the documentation

**Comment by katawful** [comment]
`SetNumericINISetting` still seems to break over repeated usage, not actually updating the camera thus requiring the console function anyways

**Comment by llde** [comment]
I will think  about this.
