### ISSUE TITLE
Flora changes with SetHarvested not saved into the savegame

### ISSUE THREAD

**Issue by Laulajatar** [llde/xOBSE#118]
The documentation about `SetHarvested` states:
> mark or unmark the calling reference as having been harvested. Changes are saved in the savegame.

They are not. 

(I so far have only tested setting harvested flora back to unharvested, not the other way around, because that seems to be the obvious use. There would be workarounds for fake harvesting a plant. Can do if necessary.)

Attached a small test plugin, steps to reproduce: 

- `coc Laula` 
- Walk downstairs, lol
- Harvest the flax
- `set testquest.doonce to 2` 
- Wait a moment until they pop back as unharvested
- Save the game
- Close the game
- Open the game
- Load the game
- Sadness.

Optionally, at each step, possible to check the output of `IsHarvested` by entering `set testquest.check to 1` and waiting a moment. `IsHarvested` works as expected. 

![Oblivion_2021-08-15_14-28-18](https://user-images.githubusercontent.com/68446748/129478625-6762e56a-0cab-4f55-a691-2f1052c1aaad.png)

[SetHarvested Test.esp.zip](https://github.com/llde/xOBSE/files/6988118/SetHarvested.Test.esp.zip)

**Comment by llde** [comment]
SetHarvest Call MarkAsModified only if the bool is 1. Can fix easily probably

**Comment by Laulajatar** [comment]
For the record, `SetHarvested 1` is correctly stored in the savegame.

**Comment by llde** [comment]
Fixed by e7a3fa3878e6af1640f7fd2b164e0d703cb70abc
