### ISSUE TITLE
MD compiled

### ISSUE THREAD

**Issue by Bxaa** [llde/xOBSE#120]
You should resume to MT by compatible reasons for all OS to prevent version mismatch and some issues

**Comment by llde** [comment]
You mean by statically link the CRT?  The AppVeyor DLL is statically linked, the release DLL is dynamically linked.
Dynamically linking the CRT has it's advantage too (the CRT code is loaded in memory for every DLL that statically link it), and for some reason statically linking the CRT introduced a delay for some users.

**Comment by Bxaa** [comment]
`You mean by statically link the CRT?`
Yep
`for some reason statically linking the CRT introduced a delay for some users`
It's unlikely that it could have anything to do with that :)

Anyway problem is solved (issue on my side)

I have a question about the 'stutter remover'. Is it possible to compile it with the latest xnvse common lib for Fallout NV?
(Judging by your sources you updated it, but only for xobse)

My projects
https://www.nexusmods.com/oblivion/mods/50381
https://www.nexusmods.com/newvegas/mods/69848

**Comment by llde** [comment]
@Bxaa For NV is recommedned to use TickFix and NVHR

**Comment by Bxaa** [comment]
TickFix and NVHR not good idea by some technical reasons...

So, SR is abandoned?

My projects: 
https://www.nexusmods.com/oblivion/mods/50381
https://www.nexusmods.com/newvegas/mods/69848

**Comment by llde** [comment]
Why not? They are way better then SR for new vegas. Yes SR is abandoned, and I have no permission to work on it  (not that I would ever touch that code, is a mess)

**Comment by Bxaa** [comment]
` I have no permission to work on it`

I thought this was your code :)

**Comment by llde** [comment]
It's not I only uploaded the code on github and fixed the project files for compilation.

**Comment by Bxaa** [comment]
I hope no one will be offended because I already made a modification of the SR :)
Now I'm making a new rendering and will post it on nexus
