### ISSUE TITLE
New line symbol for StringVar2 and sv_replace

### ISSUE THREAD

**Issue by DelmorS** [llde/xOBSE#121]
Good day to you

Is it possible somehow to write "new line symbol" inside StringVar2?

I found very old mod for Oblivion (Player's Diary by skingrad24 with scripts by Visman) and when I look through the Quest and Object scripts of the mod, I can see, that author performs String replace there with sv_replace command. And, he does replace of "new line symbol" with "br" (it is done in order to add text from MessageBox as new record to Book).

And I can not understand, how it was compiled at all, because Construction Set Script Editor (even with Extender) does not allow save and compile script, which has parenthesis on different lines!
Please, check the screen:

<img width="265" alt="Screenshot_2" src="https://user-images.githubusercontent.com/41177486/130363467-15a9ad27-5cfa-49b7-97a6-b94dca85de1e.png">

Can you please help and tell me, is it possible to compile it at all, or may be I can insert some special "new line symbol" instead of simple Enters?

Thank you

**Comment by katawful** [comment]
Use `%r` inside any string for a carriage return. If you're looking to affect HTML for books you would use literal `<br>` in the replacement string

**Comment by DelmorS** [comment]
> Use `%r` inside any string for a carriage return. If you're looking to affect HTML for books you would use literal `<br>` in the replacement string

Wow, it worked, thank you very much!
