### ISSUE TITLE
You have an unknown version of Oblivion. 

### ISSUE THREAD

**Issue by westsmyjuu** [llde/xOBSE#125]
(Hello, i trying to apply 4GB patch into oblivion.exe steam version GOTY DELUXE, but i have added polish language patch, it is possible to make it works together with xOBSE? I think it's when localization install  you have to replace oblivion.exe to this from zip. Exe from localization link on google drive:
https://drive.google.com/file/d/1PudIB-sk4Ur8gOUkK69fk-aYiYbSzOe-/view?usp=sharing

"You have an unknown version of Oblivion. Please check http://obse.silverlock.org to make sure you're using the latest version of OBSE, then send an email to the contact addresses listed in obse_readme.txt if this version is not supported in the latest release. (CRC = 0F434E4F)"

**Comment by Patrxgt** [comment]
It's already reported and will be fixed in next version. Also, for GOTY Deluxe I recommend using other language patch, than RPG'owo's one, 'cause it lacks translation for smaller DLCs and has many unnecessary files packed into it.

**Comment by westsmyjuu** [comment]
Okey, thank you for answer!

**Comment by llde** [comment]
Solved in b7890996f2f443b27277d0faaaa46ef72458a1c0
