### ISSUE TITLE
How to tell if OBSE has successfully loaded?

### ISSUE THREAD

**Issue by techmouse** [llde/xOBSE#127]
I didn't see this being asked anywhere. Is there a way to know if OBSE is loaded properly? Is there a command I type in the console or something?

**Comment by Laulajatar** [comment]
GetObseVersion

In older (x)OBSE versions there was no console output. In current ones, there is. In any way, if it shows something along the lines of "command not found", it isn't working.

**Comment by techmouse** [comment]
Well it appears it's not working then.

I'm using the Steam version. I copied obse_1_2_416.dll, obse_editor_1_2.dll, obse_steam_loader.dll, and the Data folder to the Oblivion directory, just like the instructions said. Then I just run it like normal and getobseversion gives me the standard script compile error.

Does it matter that I'm running it in Linux via Proton?

**Comment by Laulajatar** [comment]
Yes. It doesn't work like that on Linux (and sometimes, Windows fails as well).

Make a backup of OblivionLauncher.exe, rename obse_loader.exe to OblivionLauncher.exe and enjoy.
If you every verify game files or steam decides to update or something, you might need to repeat that.

**Comment by techmouse** [comment]
> Yes. It doesn't work like that on Linux (and sometimes, Windows fails as well).
> 
> Make a backup of OblivionLauncher.exe, rename obse_loader.exe to OblivionLauncher.exe and enjoy. If you every verify game files or steam decides to update or something, you might need to repeat that.

Yep, that's what I did. It worked after that with no problem.

It seems like the installation instructions or the FAQ need to be changed to reflect this.

And an extra installation step should be added to run `GetObseVersion`, just to verify OBSE is working.

**Comment by llde** [comment]
> And an extra installation step should be added to run GetObseVersion, just to verify OBSE is working.
I will change it backporting an xNVSE change that tell the user whetever it's running ro not at start

> It seems like the installation instructions or the FAQ need to be changed to reflect this.
Sorry, I forgot to add this here. It was present in the Linux page in UESP.net

**Comment by techmouse** [comment]
> It was present in the Linux page in UESP.net

Oh wow. I never knew there were Linux pages there. I'll have to remember to check there in the future. Neat stuff.

**Comment by llde** [comment]
I added a console print when OBSE is initialized. Also put the Proton bits directly in the Readme
