### ISSUE TITLE
Unable to start new Game using Proton

### ISSUE THREAD

**Issue by jscontrino** [llde/xOBSE#135]
Hi there, 

I am having trouble starting a new game on Linux using Proton and xOBSE 22.5. I have not yet tried any other versions. Steps to reproduce:

1. Vanilla install of Oblivion GOTY, no mods, no changes
2. Copy contents of 2..5 xOBSE release zip into install dir.
3. rename OblivionLauncher.exe to _OblivionLauncher.exe
4. rename obse_launcher.exe to OblivionLauncher.exe
5. start game
6. After confirming the popup that I want to start a new game, the popup disappears, but nothing happens.

About my system:
Arch, running Linux-TKG 5.16.3, KDE, RTX 2070 Super, Nvidia Drivers 510.39.01, Proton 6.3.8

I have confirmed that I can start a new game using the vanilla launcher. Any help is appreciated. Thank you alot!

**Comment by jscontrino** [comment]
I tried to launch a save file that was made with a vanilla installation of Oblivion. When trying to load that save file, I get an error message that saying "None of the master files used in this save game are loaded".

**Comment by llde** [comment]
Do you use a mod or a modmanager that redirect the profile installation? This seems like the game failing to find the Load Order data

**Comment by jscontrino** [comment]
Hi, thanks for getting back to me so fast. I understand this is probably a problem on my end, since I seem to be the only experiencing this problem, so I really do appreciate you responding to my thread. 

To answer your question: this is happening on a fresh install, meaning I un- and reinstalled the game using steam, made sure the wine prefix gets deleted too and placed the release files in the Oblivion order and renamed the appropriate files. I have no mods and/or modmanager installed.

Is there any way for me to help you help me, i.e. can I/how would I produce appropriate log files and send them to you?

Thanks again, really appreciate your work!

**Comment by llde** [comment]
I honestly not sure. IT's the Steam version of Oblivion?
I never used Proton with Oblivion, I always use directly Wine.
You may try to change the Proton Version to see if the behaviour change.
Did you use the proper OblivionLauncher at least once?

**Comment by jscontrino** [comment]
Yes, I'm using the Steam Version of Oblivion. I also went ahead and bought the GOG version for testing. I am experiencing the exact same problem using [this lutris install script](https://lutris.net/games/the-elder-scrolls-iv-oblivion/); I am unable to start/load a save. I also noticed that the problem persists even after switching back to the original launcher (or launching Oblivion.exe directly).

**Comment by llde** [comment]
The GOG version should work under Wine.
If that doesn't work for you then I belive the issue is somewhere else

**Comment by jscontrino** [comment]
Hi again. I was able to resolve the issue. Although I was unable to pinpoint the exact problem, I was able to get the steam and GOG version running with OBSE. I had to manually create the OBSE/Plugins folders and manually extracted the obse.ini to the OBSE folder. I believe the program I was using to extract the folder from ("Ark", tried via drag&drop and right click->extract inside of Dolphin) probably did something weird while extracting the folders, making Oblivion unable to properly read the Data directory. Thanks again for your support. Is there any way to support you, i.e. can I "buy you a coffee" or something else? You can consider this issue resolved.

**Comment by SASUPERNOVA** [comment]
I am writing here to verify that this is indeed an issue with Ark. Pasting and writing into the Oblivion directory from pre-extracted xOBSE22.5 (using any program, including Ark) made Oblivion work as intended. This issue appears only when files are extracted directly from Ark. An interesting thing to note is that pressing Data from the Oblivion Launcher returns this error:

> Unable to find any data files. Your Oblivion installation appears to be damaged. Please uninstall Oblivion and reinstall it from the original disc(s).

Which also confirms that Ark is doing something unintended when writing into directories. This is probably an edge case, but it may be a good idea to document this while it is not fixed on Ark's side, or in case this is not an Ark exclusive bug.

**Comment by llde** [comment]
Files for applications that are used under Wine or Proton should be extracted from windows applications (as 7-zip) not Linux ones. Unless the application has a way to make the extraction case insensitive.
