### ISSUE TITLE
Forward OnControlEvent wrong "action" reported

### ISSUE THREAD

**Issue by qwertyasdfgh2** [llde/xOBSE#142]
When using OnControlEvent with Forward key, the "action" variable in event script is always 0 - when it should be 0, 1 or 2 depending on control state. Curiously, filtering events still work, so for example, I can do:

SetEventHandler "OnControlEvent" hgoFnKeyForward "first"::0 "second"::1

and this event will correctly run only when Forward control is released, but the variable will still be 0.
I have not tested all other control types for similar issue, but Left/Right work correctly.

**Comment by llde** [comment]
Fixed by d1287be6dd23b3c0bb8de0d65568628ed2ffeb89
