### ISSUE TITLE
SetOwningFactionRequiredRank Not Accepting Integer

### ISSUE THREAD

**Issue by opiter09** [llde/xOBSE#145]
As you can see from this picture, I am passing to SOFRR an integer (7) as its only parameter, along with a calling reference that seems to be acceptable. Nevertheless, it is trying to tell me that I am missing the integer parameter.
![Screenshot (358)](https://user-images.githubusercontent.com/92452568/153771926-43f95ab9-8be5-462c-828e-b60e837f96c9.png)

**Comment by llde** [comment]
Wrong Syntax. 
You don't use () to pass arguments in legacy/obScript
it is
SetOwningFactionRequiredRank 0

**Comment by opiter09** [comment]
Your suggestion, to no-one's surprise, fixed the problem.
