### ISSUE TITLE
Refactor and feature-gate update checking code

### ISSUE THREAD

**Issue by shadeMe** [llde/xOBSE#147]
The current implementation of the GitHub API querying code in the loader needs to be disabled by default and feature-gated with an INI setting.

**Comment by llde** [comment]
89342c5a4d11345a1e053ff0e2f2a7e1f0e9ca4e and 10b598ed0d067cd0d87a3731a5772bf67ee87a75 move the winhttp code to a different compilation unit and gate behind an INI setting the feature.
