### ISSUE TITLE
MenuTapKey doesn't seem to work

### ISSUE THREAD

**Issue by qwertyasdfgh2** [llde/xOBSE#148]
Having this message in obse.log:
"MenuTapKey doesn't seem to work called from mod Extended UI.esp"

The script itself is pretty simple:
	if IsConsoleOpen
		if bConsoleFix == 0
			MenuTapKey 42;  Left Shift
			Let bConsoleFix := 1
		endif
		return
	else
		if bConsoleFix == 1
			Let bConsoleFix := 0
		endif
	endif

It used to work in the past, unfortunately don't remember on which version of OBSE.

**Comment by llde** [comment]
@qwertyasdfgh2 
fixed by 16858cae3e131dbaf4f6bdb783800235e9c5c0e8
