### ISSUE TITLE
Getting OBSE to compile a testing dll plugin

### ISSUE THREAD

**Issue by Lordkarnak** [llde/xOBSE#149]
Excuse me fellow coders for bringing up this question. I have searched through the entire tesrenewal forums, older forks, comments and some great OBSE projects on github. But I cannot find a way to compile a dll plugin for xOBSE (latest version or near latest) and older OBSE v21. I'm using Visual Studio 2015 and 2019 with the latest build tools and ATL support. No matter the version though, I run straight into the following errors:
1 - "incomplete type not allowed" caused by all static assertions in HavokCollision and NiHavokCharacters.
2 - a compilation error about va_args beings encapsulated.

I am aware a comment used to exist by user llde in tesrenewal forums but the link to it is dead.
Could you please guide me in the right direction?
Any help is greatly appreciated.

**Comment by llde** [comment]
Did you try using the example in this repo?

**Comment by Lordkarnak** [comment]
It actually compiled and a dll was made! Thank you very much!
There are still "incomplete types not allowed" errors on the same headers. Is this the expected behavior?

**Comment by llde** [comment]
No totally no. Which headers?

**Comment by Lordkarnak** [comment]
![obse_plugin_exampe error_list](https://user-images.githubusercontent.com/33664341/155815484-64f81706-5e02-4650-a7c2-829d7dd065c4.png)

Here, the errors are caused by the "common" dependency headers shown above...

**Comment by llde** [comment]
strange. Will check

**Comment by llde** [comment]
@Lordkarnak Fixed, I will commit shortly
