### ISSUE TITLE
Flag to disable console window

### ISSUE THREAD

**Issue by gravypod** [llde/xOBSE#154]
I just attempted to use xOBSE on a steam deck. The software runs fine on the deck but, whenever the user saves, the screen switches over to the console started by the loader executable. This basically locks the game until you kill it using the built in steam controls and then restart oblivion to then load the safe. Would it be possible to add a `--no-console` flag to the binary (which could be passed from steam's launcher) that hides the console?

**Comment by llde** [comment]
I will try to make the loader not to use a console at all
