### ISSUE TITLE
Bugs xOBSE 22.6.1

### ISSUE THREAD

**Issue by Pekkape** [llde/xOBSE#158]
I do not know if this has been reported or why 1 mod does not work properly with xOBSE 22.6.1 and I have now reverted back to v21.5 again until this is solved  :)

I will try to explain. I use the mod Auto Repair,  that I now also have full right to implement in my current project and I was gonna implement it very very soon by copy the script, rename it and use it from my mod. The mod is this one: https://www.nexusmods.com/oblivion/mods/38582 by Alexander Durand, username [aldurand](https://www.nexusmods.com/oblivion/users/2411014) 

The auto repair works perfect in v21.5 but it does not repair anything in 22.6.1. The loop is running, you hear the repair sound every 3rd second but nothing gets repaired. I had some items at 125 before I switched to v22.6.1 and now some at 100 aftyer I upgraded. My char is master armourer and should repair everything to quality 125 in an instant after a fight.  When i took a peek in inventory, I do not recall seeing anything under quality 100. Well something is not working. Maybe we can figure out together what is failing?

What have I tested more? Well Denock, autoloot and some scripts that I use every day, so I am very happy with 22.6.1 so far, until I went to a dungeon fighting and trying to repair my loot. xOBSE is getting better for me and the way I play, no doubt. Reverting back to 21.5 made the game to freeze first and I logged out from windows, logged into the game, and the reverting worked perfect. A pop up came up, telling me I now run 21.5 and OBSE has reverted. All loot was repaired to 125 instantly.

As I now have the right to use and edit the script as I see fit. Do I need to change it in any way to make it work with v22.6.1?

I can add the script here if needed. Maybe it is easiest?

**Comment by llde** [comment]
Thanks, I will check when I have time

**Comment by llde** [comment]
@Pekkape If you are still around, can you provide a savegame with damaged items, that can be load with a bare load order?

**Comment by llde** [comment]
I did fix the issue. I lloked at the script and I believe that instead of using GetItems and GetInvRefsForItem you can  simplify by using a for each  container loop  directly.
you can also try removing the RemoveMeIR target, as the current iteration of Inventroy References is way less bugged then before.

**Comment by Pekkape** [comment]
Thanks for all support Idle. Do you still have the script? I could maybe
fix it myself, maybe?  I am not the author of the script but I have rights
to use it and implement it in my own mods, so I need to fix it in any way,
but if you still have the already edited and fixed script saved, I would be
happy as a nice loudly fart and will burst in joy.  :D

And I am still around, I do not plan to go anywhere...  ;)  Not until I
pass out at least...  ;)



Per-Erik Petersson

Nick: Pekka - The dreamer :D

PePromus Designs, Ideas, Dreams and Solutions
<https://pepromusdesign.blogspot.com/> - The dream project - No limits
allowed.

https://pepromusdesign.blogspot.com/

Facebook <https://www.facebook.com/pererik.peterson/>

YouTube <https://www.youtube.com/channel/UCWglfNAdO9-_0RjVi2imasQ>

Email ***@***.***>: ***@***.***

LinkedIn <https://www.linkedin.com/in/per-erik-peterson-30a9aa182/>

Flickr ***@***.***/with/50787951166/>

------------------

Also a hobby game designer, well I used to do that at least for 15 years,
from time to time. That odd stuff is also on YouTube,

------------------



Den lör 23 juli 2022 kl 17:45 skrev llde ***@***.***>:

**Comment by llde** [comment]
The script now works with the last commit, I just suggested an optimization that I didn't test
