### ISSUE TITLE
xOBSE Hated by older mods 

### ISSUE THREAD

**Issue by Davitto94** [llde/xOBSE#160]
Hi guys! Thankyou for all your work on xOBSE.
There is just one mod that has stopped working for me ever since I used xOBSE. For years I could use "Put it in its Place - Enhanced Grabbing" out of the box without issue. Now it seems to not function. It's usually when I make a few saves in a new character. It will work up until it decides not to. So "Enhanced Grabbing" is a mod most of you guys would know about. It changes the crime steal mechanic so that when you use the Z key to touch an item that isn't yours you won't instantly be accused of stealing it.
Well you see, that important feature no longer works. I have used this mod without issue for a long time. But now it's becoming too out of reach because of its age. I can't remember the exact details of other mods that didn't work. But I know that any mod older than a 2011 update seems to hate xOBSE
Also worth adding that I tried turning off the crime system in the mod and it fixed it but only for a little while. If I touch an item like a broom I will be sentenced to death. Everyone will attack me for my blood and then when I load a save before this happens the game crashes. I don't use any save mods like Better Saves or any save Timers. I just use the vanilla hard save feature.

**Comment by Davitto94** [comment]
Ignore the second comment. Issue still persists

**Comment by llde** [comment]
I did multiple testing and it's working for me. Picking an owned item doesn't trigger bounty automatically. Are there specific conditions for the bug to trigger? @Davitto94
