### ISSUE TITLE
Windows 11 Insider - Issue with latest Insider Release

### ISSUE THREAD

**Issue by WolfRevo** [llde/xOBSE#162]
Hi,

the latest Windows 11 Insider Release 25140.1000 causes obse to stop working. Unfortunately the information seen is not sufficient to have a glue if this is a bug which will be fixed with one of the next Insider Releases or if this is a new mechanism for security inside of Windows 11. Also the [release notes](https://blogs.windows.com/windows-insider/2022/06/15/announcing-windows-11-insider-preview-build-25140/) don't give me a hint.

Screenshot 1: proposed way to load obse via MO2 directly (dll configured for oblivion.exe) ![obse_inline](https://user-images.githubusercontent.com/38487435/174443416-836c1814-4830-4222-8d24-7d1506b06f13.png)
Screenshot 2: direct loading using obse_loader.exe via MO2 (at least some more information) ![obse_outline](https://user-images.githubusercontent.com/38487435/174443417-2198c361-ce6a-4e76-9751-9d77f667ec9a.png)
Screenshot 3: Windows 11 version check 
![winver_2022_06](https://user-images.githubusercontent.com/38487435/174443418-6e3c9bc4-8192-4b14-a514-316ee3ffa45b.png)

Any ideas? For sure I can collect more information if you tell me how to (e.g. debug version of obse or whatever you use to identify issues).

**Comment by WolfRevo** [comment]
Unfortunately it also happens on the next Insider build:
![grafik](https://user-images.githubusercontent.com/38487435/175115486-87fd7ee6-b344-434a-8c51-cd694528e986.png)

**Comment by llde** [comment]
I will see this in the next days

**Comment by llde** [comment]
I'm testing with 25145.1011 and it's working fine

**Comment by Morrofall** [comment]
I can report, xOBSE works fine on the latest insider, I had 2 reinstalls same result.

**Comment by llde** [comment]
Reopen if the issue represent
