### ISSUE TITLE
Unknown version of Oblivion

### ISSUE THREAD

**Issue by TheeminPL** [llde/xOBSE#166]
Hello, I have DRM Removed Polish Version with 4GB Patch and OBSE doesn't recognise it.

"You have an unknown version of Oblivion. Please check http://obse.silverlock.org to make sure you're using the latest version of OBSE, then send an email to the contact addresses listed in obse_readme.txt if this version is not supported in the latest release. (CRC = BF654A48)"

**Comment by llde** [comment]
Send the oblivion.exe

**Comment by TheeminPL** [comment]
https://drive.google.com/file/d/1WMLPUypwQwK1OD5xKNwr6HJYdaTKp7LN/view?usp=sharing


pon., 8 sie 2022 o 14:34 llde ***@***.***> napisał(a):
