### ISSUE TITLE
xOBSE / OBSE

### ISSUE THREAD

**Issue by ss3105** [llde/xOBSE#181]
Hi. I'm in NexusMods page, just about to download "Oblivion reloaded" Mod (https://www.nexusmods.com/oblivion/mods/52191).
And it requires xOBSE. I have OBSE installed already. Should I install xOBSE instead, or is OBSE just fine?
May I get bugs if I use xOBSE with some old mods?

**Comment by llde** [comment]
for OR OBSE or xOBSE should be  interchangable.  There are some issues for some mods in xOBSE I need to investigate (you can check here). If you use a know problematic mod then stick with OBSE or better  one of the first xOBSE iterations (xOBSE 21.8) (most issues were related to InventoryReference changes that happened only from xOBSE 22.0). If you don't use a mod wth know issues then you can use the latest version
