### ISSUE TITLE
 message saying "The latest Oblivion Script Extender is not detected. morroblivion requires the latest version of xOBS€ to run, Please exit the game now and check your installation"  I am using xOBSE 22.7.

### ISSUE THREAD

**Issue by ThaalSinestro** [llde/xOBSE#195]
Message saying "The latest Oblivion Script Extender is not detected. morroblivion requires the latest version of xOBS€ to run, Please exit the game now and check your installation"  I am using xOBSE 22.7.

**Comment by Murriden13** [comment]
Did this ever get solved?
