### ISSUE TITLE
OnControlEvent returns wrong "action" when triggered by mouse buttons

### ISSUE THREAD

**Issue by qwertyasdfgh2** [llde/xOBSE#196]
Controls that are bound to mouse buttons (I tested block and attack) return wrong action type in OnControlEvent.
Instead of 0 for press, 1 for release and 2 for hold it's 0 for press (correct), 1 for hold and nothing (?) for release.
Same event script works correctly if triggered by keyboard button.

**Comment by llde** [comment]
Thanks for the report I will try to resolve shortly

**Comment by llde** [comment]
@qwertyasdfgh2 Can you check wethever OnKeyEvent is affected too?

**Comment by qwertyasdfgh2** [comment]
No, OnKeyEvent works correctly with mouse buttons.
