### ISSUE TITLE
GetAlchMenuApparatus doesn't work as documented

### ISSUE THREAD

**Issue by qwertyasdfgh2** [llde/xOBSE#205]
Official OBSE documentation says that GetAlchMenuApparatus returns as follows:

0: Mortar and Pestle
1: Retort
2: Alembic
3: Calcinator

While in reality it is:

0: Mortar and Pestle
1: Alembic
2: Calcinator
3: Retort

Since this is an existing function, it's probably best to just fix the documentation?

**Comment by llde** [comment]
Hi, @qwertyasdfgh2 
Can you confirm wehtever this mapping is followed by other appraratus type functions like GetApparatusType?

**Comment by qwertyasdfgh2** [comment]
Thanks, and yes, GetApparatusType follows second mapping.
The first is the order in which apparatus appear in alchemy menu, that's probably why there's confusion
