### ISSUE TITLE
Wont work - Application Ioad error 5:0000065434

### ISSUE THREAD

**Issue by billi95** [llde/xOBSE#222]
I bought the game on steam (As this mod does not work on the Xbox game pass version)

Downloaded the mod via vortex following the instruction:

1. Click the "Vortex" button in the top-right of this page.
2. Once installed and enabled, ensure you have deployed it by clicking "Deploy Mods" on the Mods toolbar.
3. Use the shortcut on the dashboard to start the game with OBSE. 

But when I do that I get a window with "Application Ioad error 5:0000065434".

I tried the solution from problem #206 but that did not help at all (Rename obse_loader.exe to OblivionLauncher.exe and Launch OblivionLauncher.exe to play the game.) 

Some people on the discord claim to simply start the game via Steam and OBSE would hook itself in but I cant confirm that. 

How do I get this mod running?

**Comment by llde** [comment]
Can you test the last beta from github?

**Comment by billi95** [comment]
I have no idea how I download anything from github :D (I was never  a big fan of the design)

**Comment by llde** [comment]
got to Releases pick last release and download the zip

**Comment by billi95** [comment]
Done and installed it via Vortex. Works like a charm now!

Question: Does this beta version also works with the Oblivion from Xbox Game Pass?

**Comment by llde** [comment]
No. OBSE not working with gamepass is not a version issue per se, it's the protections gamepass involves that make this difficult or impossible
