### ISSUE TITLE
TapKey not simulating all keycodes properly in MenuMode

### ISSUE THREAD

**Issue by DisasterGoneAwesome** [llde/xOBSE#231]
TapKey does not work for some keycodes while in MenuMode.

[Better Menu Controls](https://www.nexusmods.com/oblivion/mods/48144) stopped working correctly after obse22.2. After the hotfix (22.3) OnKeyDown seems to be working again, but the mod still doesn't work properly, although some functionality works fine.

After some investigation, TabKey seems to be the culprit. While in MenuMode simulating arrow-key and enter presses does not work. On the other hand, simulating Tab or F1 works fine.

This is how I tested it [DGA_TapKeyTest.zip](https://github.com/user-attachments/files/16116438/DGA_TapKeyTest.zip).
Tested on a new savegame with no other mods installed. I also remapped the movement controls to the arrow keys (from wasd) and simulated keypresses work fine in GameMode.

**Comment by slowpard** [comment]
Can confirm this, tried to simulate arrow presses to autonavigate a custom menu, doesn't work.

**Comment by llde** [comment]
Hi @DisasterGoneAwesome 
the provided testcase is in fact wrong. It use TapKey to ask for keypresses for the UI, but the UI manage this stuff differently requiring MenuTapKey.  TapKey in menu works only for some keys whose handling is managed by the Input poll directly.
This is not a bug and certainly not a regression. I remade the test case using OnKeyDown for the i -> Upper Key and tested on OBSE 21.4 and the behavior is the same.
Now there is in fact a bug where MenuTapKey seems to not working.

**Comment by llde** [comment]
@DisasterGoneAwesome  should be fixed in  commit 55a5635

You can test the file from this action: https://github.com/llde/xOBSE/actions/runs/10390492938

**Comment by slowpard** [comment]
Confirm that MenuTapKey works as intended now.
