### ISSUE TITLE
CTD on heavy modded game or weak PC, when removeallitems on player.

### ISSUE THREAD

**Issue by GBRPlus** [llde/xOBSE#234]
just comment this in xOBSE please)

**Comment by GBRPlus** [comment]
WriteRelCall (kRemoveAllItems_PatchAddr, (UInt32)&RemoveAllItemsHook);
	WriteRelCall (kGotoJail_PatchAddr, (UInt32)&RemoveAllItemsHook);

**Comment by llde** [comment]
fixed in aaaefe1
