### ISSUE TITLE
Another version of Oblivion.exe

### ISSUE THREAD

**Issue by vlad196** [llde/xOBSE#236]
Please, add oblivion.exe v.1.2.0416 1C Gold edition (russian localization). 

This is a modified version of the file, adding a no-CD.
This version is the result of byte substitution and does not have anyone's signatures (tags, names, "...was here", etc):
```bash
printf '\xE9\x67\x01\x00\x00' | dd conv=notrunc of=Oblivion.exe bs=1 seek=$((0xD627))
```
**Modified file (need to add):**
https://drive.google.com/drive/folders/1MiVgEWU2Sf8XHB94tibRQ8ck5pcHiSEk?usp=sharing

Original file (for comparison):
https://drive.google.com/drive/folders/19C7BqV5zIIcRV6tRXUXTeE4bzo6D314_?usp=sharing

**Comment by llde** [comment]
Is the file made by you? 
Is the original file included in the supported checksums?
0xD627 seems a strange address to hook for this.

**Comment by vlad196** [comment]
Yes, I did. I took another modified file and looked at what was changed in it.
file:
https://drive.google.com/drive/folders/1w9i0_kcN00zQ-p-eWYXpMEg3PnLsBBTb?usp=sharing

The original and file above launch with obse_loader, but i'm not sure how check checksums

I tried crc32, but none of the files matched the amount in obse/loader_common/EXEChecksum.cpp. Even original file.

Can you tell me how to check it? Linux or Windows, whatever.

**Comment by llde** [comment]
You can check if the original file can be started by the launcher.

**Comment by vlad196** [comment]
> You can check if the original file can be started by the launcher.

yes, the original file started by the obse_launcher.



> Waht difference there is between the last file you linked and this https://drive.google.com/drive/folders/19C7BqV5zIIcRV6tRXUXTeE4bzo6D314_?usp=sharing (the second file linked in the first post)?

You may have meant the first link and the link in the second post. The difference is that the first link has only a no-cd, the link in the second post has an additional signature:
```
SAGE486DX  was here ;)
```
![Снимок экрана_20240813_092711](https://github.com/user-attachments/assets/10521dba-ba54-4c8a-80e7-d545820d0d90)

I suppose many exe's have the same way for no-CD, but have their own signatures. If you know how to do it yourself, it's inconvenient to additionally record someone's signature, especially when you're making a script.

In general, I came to modify the file myself because the file SAGE486D, which is suitable for 1C Gold edition I found only on two sites, and I'm afraid that someday they will be lost. And since I came to the independent modification, then there is no sense in the mandatory repetition of someone else's signature to run the game

>the second file linked in the first post

The second link in first post is the original file from disk. Without changes.

**Comment by llde** [comment]
But at this point, why editing the exe instead of patching the check routine in an obse plugin?

**Comment by vlad196** [comment]
I didn't know it could be done any other way.
If it is possible in obse plugins and you recommend it, I will then do it like the plugin and close the issue :)

**Comment by llde** [comment]
yeah, I did it myself for my retail version of the game (but I have different offsets, would need to check which ones are better )

**Comment by vlad196** [comment]
Sound's great!
Can I see how you made the plugin? The example in there is very extensive, and I don't know C++ well

**Comment by llde** [comment]
just need to use the OBSE_Load function to install the Jmp hook (WriteRelJump function). All the other stuffs from the example can be safely removed (except the OBSE_Query function)

technically you don't even need C++, a C project would be enough.
