### ISSUE TITLE
Crashes when specifying a path containing multibyte characters in the FileExists function

### ISSUE THREAD

**Issue by rnruxn773** [llde/xOBSE#237]
Since xOBSE-22.10beta2, specifying a path containing non-alphanumeric multibyte characters such as Chinese or Russian in the FileExists function causes an immediate crash. 

The issue can be reproduced with the following code:

```
scn testquestscript

string_var filepath

Begin GameMode

	if GetGameLoaded
		let filepath := "Data\ini.ini"
		
		; Passed
		printc "check 1 : %z" filepath
		if FileExists $filepath
			printc "check 1 : %z found!" filepath
		endif

		let filepath := "Data\ini_к файлу_文件路径.ini"
		
		; Not passed
		printc "check 2 : %z" filepath
		if FileExists $filepath
			printc "check 2 : %z found!" filepath
		endif

		sv_Destruct filepath
	endif
End
```

**Comment by llde** [comment]
I'm afraid you are mixing characters from 2 different locales, I'm not sure how conversion function for CP_ACP codepage can react. I Will try to not make the function crash however.
A workaround may be, maybe, to use directly the complete string instead of composing ti with stringvars.

**Comment by rnruxn773** [comment]
Sorry for the confusion, but mixing characters from two different locales was just an example for the sample code. In reality, the function should crash if it contains any multibyte characters, regardless of the locale. My Win 11 is set to the Japanese locale, and I've confirmed that it crashes even when only Japanese characters are included. This happens with or without the Japanese localization patch (OBJA).

**Comment by llde** [comment]
Hi, I reproduced the crash with the sample script,  I had to force japanese locale on my end too. Crash happens inside DoStringExtractHook.

**Comment by rnruxn773** [comment]
I tried 4988c0d, and the crash no longer occurred. Thank you for the quick fix!
