### ISSUE TITLE
Standardization of sourcecode

### ISSUE THREAD

**Issue by llde** [llde/xOBSE#28]
This source is passed beetween many hands, everyone with his style of programming.

We have inconsistences beetween how things are done: most of the time functions use pointers, sometime (as in HasSpell) use references, or difference about getting Actors\* from TESObjectREFR*
sometimes directly casted ((Actor_)thisObj for example) other times a TESObjectREFR is dynamic-casted to Actor_.

@shadeMe  I suggest that **when possible** we should review the various difference and adopt one of them as standard. 
What do you think?

**Comment by shadeMe** [comment]
The rule of thumb is that we need to use dynamic-casting when we're casting an object across the class hierarchy. If the destination class is a direct descendant of the base class, then the pointer fix-ups aren't required and a regular reinterpret_cast would work. The choice of casting is also dependent on performance concerns as the latter is slower that a C-style cast.

I'd stick to using pointers for internal game classes and references for STL classes. That's also the general style the code follows, if I'm not mistaken. Of course there are probably a few exceptions here and there but I'm disinclined to refactor the existing code to adopt a new "standard" (wouldn't be a productive exercise, especially when it doesn't contribute much to the project's technical debt).

**Comment by llde** [comment]
I was mainly talking about taking a style of code already present and adopt it in new code,  more then refactoring the current code, unless there is really an ambiguity.
However there is no need.
