### ISSUE TITLE
GetDisease is unimplemented

### ISSUE THREAD

**Issue by llde** [llde/xOBSE#29]
@shadeMe  I saw various dialogue (expecially hellos) making use of GetDisease.
I know that it was never implemented for scripts. But it was implemented for dialogue condition?

**Comment by shadeMe** [comment]
I wouldn't call it a bug per-se if they weren't implemented as script commands. It's mostly likely that the dev's didn't need it in a regular script's context. But callable versions of the commands could be added to OBSE.

**Comment by llde** [comment]
Well I added a replacement function that should work.  However before replacing I want to test if it wa simplemented as condition functions

**Comment by llde** [comment]
I tested and the result is that GetDisease is not implemented neither as conditional function despite having some dialogues that use it.
Do you think that we can replace the Getdisease functions with the obse implementation directly?

**Comment by shadeMe** [comment]
We'll need to make sure that that GetDisease's the same as IsDiseased. Is that the conclusion you reached after reviewing the dialog records that use it?

**Comment by llde** [comment]
Yes I came to this conclusion.

**Comment by llde** [comment]
Separating GetDisease and SetAtStart issues.

Getdisease is implemented. Also callable as IsDiseased.

**Comment by llde** [comment]
Fixed in 4125a5d215a564f907aee6aef4d98c4f5c5cecc0
