### ISSUE TITLE
sv_ToNumeric doesn't accept array entries

### ISSUE THREAD

**Issue by shadeMe** [llde/xOBSE#31]
Make sv_ToNumeric accept array entries as parameter (like "let MyNumber := sv_ToNumeric  MyArray[0]" ).  Currently accepts only string vars ("Let MyNumber := sv_ToNumeric MyString).

**Comment by QQuix** [comment]
Forli's issue #33 sort of supersedes this one.
Adding support for array elements to his request should do .
