### ISSUE TITLE
Add note in the docs about passing ref vars as UDF args to Call

### ISSUE THREAD

**Issue by shadeMe** [llde/xOBSE#34]
Passing functions as ref vars to the Call command bypasses the compile-time type checking. While this is advantageous (makes UDFs first-class objects of a kind), it's a currently undocumented feature.

**Comment by Forlini91** [comment]
I wonder if it's possible to achieve something similar with commands too. I mean something like this:
Let refVar := StoreCommand IsSneaking
Let cmdResult := PlayerRef.Call refVar
Let refVar := StoreCommand GetAVC
Let result := PlayerRef.Call ref1 8

Anyway, I don't know what would happen with something like this:
Let refCMD := StoreCommand Call   ;yes... that's it!
Let refUDF := someUserDefinedFunction   ;it needs a Short argument
Let result := Call refCMD refUDF 5   ;Call command Call, passing the function and its Short argument

**Comment by shadeMe** [comment]
I can think of a few issues one would run into implementing something like this off the top of my head. That said, I can't come up with any use case where this would be useful. It'd only add more overhead to what would otherwise be a straight-forward command call.
