### ISSUE TITLE
GetFirstRef with form type filter ignores deleted references

### ISSUE THREAD

**Issue by Forlini91** [llde/xOBSE#37]
As the title says, using GetFirstRef (and other cell scan commands) with a form type filter (other than 0/None) makes the command ignore references marked for deletion, but still not deleted.

Since altering this behaviour may alter the behaviour of existing scripts, I propose to add another optional parameter includeDeletedRefs:int, which allow the commands to include those references.

**Comment by llde** [comment]
Ok I added an optional parameter for including deleted references (1 including, 0 excluding).

Also added filter type 90 to only return deleted references.

Need extensive test. 
@Forlini91 can you or lubronbrons test if this solve the need of your tests cases?
Please report.

**Comment by Forlini91** [comment]
Ok, the command seems to work as expected, but I have noticed something in the code and in the tests:
In Commands_MiscReferences.cpp:
```
class RefMatcherActor
{
public:
	bool  m_includeDeleted;
	RefMatcherActor(bool includeDeleted) : m_includeDeleted(includeDeleted)
		{ }

	bool Accept(const TESObjectREFR* refr)
	{
		if (refr->IsDeleted() && !m_includeDeleted)
			return false;
		else if (refr->baseForm->typeID == kFormType_Creature)
			return true;
		else if (refr->baseForm->typeID == kFormType_NPC && refr->baseForm->refID != 7) //exclude the player
			return true;
		else
			return false;
	}
};
```
specifically:
`... && refr->baseForm->refID != 7)`
This filter is only applied when you use the form filter for actors. When you don't use any filter, the player reference is included. Is this intended?

**Comment by llde** [comment]
You should ask to the one who originally wrote  the code.I really don't  know. 
I'm closing the issue

**Comment by llde** [comment]
Close in c8386b1cd7c758685797ac0320238735078ff9f1
