### ISSUE TITLE
GetBaseAV2 badly implemented.

### ISSUE THREAD

**Issue by claustromaniac** [llde/xOBSE#42]
I've read very old posts where people said it worked differently for them, but for me it seems to include fortify abilities just like GetBaseAV.

**Comment by claustromaniac** [comment]
I took the liberty of making a plugin to demonstrate this issue, since I don't really expect anyone to trust too much in my sole word (since I'm basically a random lurker in the Oblivion modding community).

GetBaseAV2 is definitely flawed, but the issue is more far-fetched than I first said.

The plugin adds two global scripts and three spells: a drain ability, a fortify ability, and a spell to dump GetBaseAV2 results to console as opposed to GetBaseAV results.

The drain and fortify abilities affect all attributes and health, and have a magnitude of 10.

These are my findings: for attributes GetBaseAV and GetBaseAV2 return exactly the same, with or without fortify/drain abilities (which totally sucks). Health however is an entirely different story... 

Real base value: 80
I add the fortify ability...
GetBaseAV Health = 80 (nothing new here)
GetBaseAV2 Health = 70 (OK, correct value)

Then I add the drain ability on top of that...
GetBaseAV Health = 50 (that's weird)
GetBaseAV2 Health = 30 (that's even more weird)

Then I _remove_ the fortify ability...
GetBaseAV Health = 20
GetBaseAV2 Health = 10 ( . . . )

The plugin in question.
[TEST GetBaseAV2.zip](https://github.com/llde/Oblivion-Script-Extender/files/398650/TEST.GetBaseAV2.zip)

**Comment by llde** [comment]
Thanks for reporting @claustromaniac . I have deeply rewrote the function, and it seem to report at least values that seem corrects. There is a bug with magicka and energy being affected by health Drain/fortify effects, and maybe it's true also the reverse.
Can you do more test?

**Comment by claustromaniac** [comment]
Great job, overall. It now works mostly fine.

I tested it just now and I can confirm the function takes into account health drain and fortify abilities when measuring magicka and fatigue base AVs, as if the actor had been affected by a magicka or fatigue fortify/drain ability of the same magnitude. This doesn't seem to happen the other way around, i.e. fortify magicka and fortify fatigue abilities don't seem to affect the calculated result of the other base AVs.

I noticed something weird that I believe is completely unrelated, but still worth a mention: in my tests, drain magicka/fatigue abilities with a magnitude of 10 forced the respective AVs to 65666. I didn't bother checking why or how, but this time I tested in a nearly vanilla setup, with just Oblivion.esm and a new test plugin. Is there any known reason for that to happen?

**Comment by llde** [comment]
This should not happen. Seem a case of integer underflow

**Comment by llde** [comment]
@claustromaniac GetBaseAV2 should be finally implmented correctly. Please test with the lat changes.

**Comment by claustromaniac** [comment]
Alright, I didn't get to test it extensively yet, but it seems to return consistently appropriate values now. 

The only weirdness I can still see is about the drain fatigue/magicka abilities setting their respective AVs to 65666 without any apparent reason at all but, as I said earlier, I believe it's unrelated. I think so because the very first time I tested GetBaseAV2 (before opening this issue) I didn't actually get to test drain fatigue and drain magicka abilities, so I think the same would've likely happened back then if I did. Also, I don't see why there should be any kind of automatic correlation between an evaluation function such as GetBaseAV2 and the way a specific drain or fortify ability affects an AV (GetBaseAV returns 65666 too in those cases, and the menu displays that value as well).

This time I tested in a completely vanilla setup, with just Oblivion.esm + OBSE. No OBSE plugins either. 

I'm going to test a bit further. So far the function itself works fine though, so I guess you can close this issue in the meantime if you want.

Great job!

**Comment by llde** [comment]
I  think is a bug on the calculation in the function taht apply the drain effect. Thanks for the testings

**Comment by llde** [comment]
Resolved by deprecating GetBaseAV2 (to avoid breaking compatibility with mod requiring that beheviour) and adding a new GetBaseAV3
Fixed in 84ff0157510aa60ce732ce0da84ff4c2cad86a91
