### ISSUE TITLE
ExtractArgsEx and ExtractFormatStringArgs visibility

### ISSUE THREAD

**Issue by llde** [llde/xOBSE#54]
@shadeMe  There is any reason becouse ExtractFormatStringArgs and ExtractArgsEx are restricted in OBSE_CORE, while previously they were directly callable by plugins (OBME source is an example of this)?

**Comment by shadeMe** [comment]
That was done when the compiler override was implemented (both those functions had to be modified). Plugins can still call those functions through the plugin script interface.

**Comment by llde** [comment]
Which is the difference between ExtractArgsEx and ExtractArgs? 
With and without compiler override.

**Comment by shadeMe** [comment]
ExtractArgs is the argument extraction method that all vanilla commands use. The -Ex version is the same as the vanilla version with the exception that it doesn't perform any type checking on form arguments. The -Ex version is the preferred one in most, if not all, cases.
