### ISSUE TITLE
GetFormFromMod description

### ISSUE THREAD

**Issue by claustromaniac** [llde/xOBSE#59]
> The formID must be passed as a literal value as script variables don't have the precision necessary to store all possible formIDs.

Am I the only one finding that statement rather weird? If the function is meant to take two strings as arguments, I don't see why there would be any problem with precision - and there isn't, in practice.

**Comment by llde** [comment]
You are right:
fixed in dd56b0d3c9350e58e2b35b27f38a5773e38f83f5
