### ISSUE TITLE
Incorrect error message in obse_plugin_example

### ISSUE THREAD

**Issue by Troy1010** [llde/xOBSE#61]
This is obviously not a high priority issue but..
In obse_plugin_example's main.cpp, line 437
`	_MESSAGE("OBSE version too old (got %08X expected at least %08X)", obse->obseVersion, OBSE_VERSION_INTEGER);`
should be:
`	_MESSAGE("OBSE version too old (got %i expected at least %i)", obse->obseVersion, OBSE_VERSION_INTEGER);`

The version int shouldn't be cast as hex for the print.
The log incorrectly reads:
`OBSE version too old (got 00000015 expected at least 00000016)`
Instead of:
`OBSE version too old (got 00000021 expected at least 00000022)`

**Comment by llde** [comment]
Just a cosmetic issue, I would say. When I will commit again, I will fix.
(It should probably be %u instead)

**Comment by llde** [comment]
fixed in fa249cf6b4733cb8f28a19212e90829330e820d3
