### ISSUE TITLE
atltypes.h missing

### ISSUE THREAD

**Issue by GodschildGaming** [llde/xOBSE#62]
So I  tried following the thread here https://tesrenewal.com/comment/84757#comment-84757 but now get this error `Severity	Code	Description	Project	File	Line	Suppression State
Error	C1083	Cannot open include file: 'atltypes.h': No such file or directory	obse_plugin_example	c:\users\godschild\desktop\oblivion-script-extender-master\obse\stdafx.h	22	
`

**Comment by llde** [comment]
Need the ATL library installer from visual studio
