### ISSUE TITLE
OBSE incompatibility.

### ISSUE THREAD

**Issue by Magnitudo58** [llde/xOBSE#69]
Hello!
I own Oblivion from Elder Scrolls Anthology. The problem is that polish publisher Cenega deleted DRM files or something to make it playable without a disc (it's a retail version), and that changed its CRC code and now OBSE doesn't work. Any ideas what can be done?
EDIT: The CRC code that pops up is "9E284932".

**Comment by llde** [comment]
[loader.zip](https://github.com/llde/xOBSE/files/5299350/loader.zip)


Can you try with this loader?

**Comment by Magnitudo58** [comment]
The game started and in game files appeared text-file called "obse", so I think it works. Thanks!
