### ISSUE TITLE
Weird behaviour of RemoveMeIR

### ISSUE THREAD

**Issue by Laulajatar** [llde/xOBSE#70]
Removing items with RemoveMeIR from the player leaves something behind.
Lets say you remove all your apples from your inventory with RemoveMeIR. If you look at the inventory (F2), there are no apples. But if you check it with GetItemCount, it will still return 1 apple, which you can remove with RemoveItem, after which GetItemCount correctly returns 0.
I have not yet tested if it also happens with containers/npcs.

**Comment by llde** [comment]
Please do check and report.

**Comment by Laulajatar** [comment]
I tried every combination of npc, container, player and nothing (no target) that I could think of, it seems that there is always one "item" left. 

[Successful Static Log.log](https://github.com/llde/xOBSE/files/5314437/Successful.Static.Log.log)

"Test" is the player. Basically added 5 TestObj, did a loop in which I used RemoveMeIR on that found object and checked the amount afterwards.

**Comment by llde** [comment]
Can you upload the test ESP?

**Comment by Laulajatar** [comment]
[RemoveMeIRTest.esp.zip](https://github.com/llde/xOBSE/files/5319030/RemoveMeIRTest.esp.zip)

**Comment by llde** [comment]
Prevfious fix intorduced a serious instability. Reverting and reopening for now

**Comment by llde** [comment]
Fixed for good this time
