### ISSUE TITLE
In-menus are off

### ISSUE THREAD

**Issue by JerimiahOfficial** [llde/xOBSE#83]
When entering the main menu when you hover over the buttons or what are perceived to be the buttons they don't seem to function. Instead, I have to hover some space above the button for them to work, this is the same for any of the other menus including the settings, inventories and popups. This is on a fresh install with the latest version of xOBSE without any other mods being installed.

**Settings:**
![image](https://user-images.githubusercontent.com/38990407/106159790-2708cc80-6153-11eb-8556-ee36368863b3.png)

**Issue:**
[https://www.youtube.com/watch?v=ZB-PK3QmfCc](url)

**Comment by Laulajatar** [comment]
Did you delete your ini when you did a fresh install? Make sure your fov is 75 and you have no other mod messing with it. That is not hwo the main menu is supposed to look. 

`fDefaultFOV=75.0000`

**Comment by JerimiahOfficial** [comment]
> Did you delete your ini when you did a fresh install? Make sure your fov is 75 and you have no other mod messing with it. That is not how the main menu is supposed to look.
> 
> `fDefaultFOV=75.0000`

Fov was set to 120.0000 Thanks for the help!
