### ISSUE TITLE
v22 crash when looking through apparel in inventory

### ISSUE THREAD

**Issue by Hotdog3223** [llde/xOBSE#88]
I'm playing Morroblivion 65 and I'm around 50 hours into the game. Everything had been working perfectly, virtually no crashes and just finished the MQ recently. I have a lot of Cast on Use items in my inventory and am using the NorthernUI reskin which made them incorrectly show as constant effect items.

 I just saw today that this new version of xOBSE got released, and I thought this new version was supposed to make them display correctly as Cast on Use.

But when I'm looking through them they all still show Constant Effect and now it crashes before I'm able to get half way through all of them

**Comment by llde** [comment]
There is a regression in some handling of extradata list,  you have an alchemy or hotkeys mod installed?
In case try to provide a backtrace.

Regarding the CWU, this release resolve an issue in using the keyboard selection, but it seems there is a separate issue with NUI if you use the complete version, maybe related to the tile name. It should work with NUI Away without the ui reskin.

**Comment by Hotdog3223** [comment]
I don't have any alchemy or hotkey mods installed. NorthernUI's reskin does come with its own alchemy menu though. 

How do I provide a backtrace?

**Comment by llde** [comment]
You need a debugger or a crash logger.

In case you may also try to activate OBSE minidumps and send me these

**Comment by Hotdog3223** [comment]
[CobbCrashLogger.log](https://github.com/llde/xOBSE/files/6230084/CobbCrashLogger.log)

**Comment by Hotdog3223** [comment]
I think it crashed specifically on the Amulet of Heartheal

**Comment by llde** [comment]
It's consistently reproducible on the same item?
This is a different crash location that the other issues.
Thanks, I will try to look at it but CobbCrashLogger while nice is goddamit hard to read, expecially it miss a  calltrace.

**Comment by Hotdog3223** [comment]
Well, I looked through my inventory which had a lot of different Cast on Use items but this time I had put half of them into a barrel before updating xOBSE again. None of the items in my inventory made it crash but when i went into the barrel to look through them I think it crashed on the Amulet of Heartheal.

That specific amulet is from Morroblivion, you get it from one of the dagoths. 

https://en.uesp.net/wiki/Morrowind:Amulet_of_Heartheal

**Comment by llde** [comment]
@Hotdog3223 can you check if your ctd persist with this dll?
https://ci.appveyor.com/project/llde/xOBSE/branch/master/job/glawcblsrcrsc228/artifacts

**Comment by Hotdog3223** [comment]
That fixed the crashing.
