### ISSUE TITLE
Crash if you use getBaseAV3 for invalid actor values on creatures

### ISSUE THREAD

**Issue by SMUnlimited** [llde/xOBSE#89]
OBSE v21.8: Game crash when calling `getBaseAV3 Destruction` on a creature, presumably because creatures do not have certain actor values and function does not handle that its missing.

But super easy Workaround: If you check for `IsCreature == 0` first before calling you will avoid the crash.

Update: Also seems to crash if the player has not yet picked class yet, so calling getBaseAV3 on the player in a new game also crashes the game.

**Comment by llde** [comment]
Does the old GetBaseAV2 manifest the same crash? What AV were you trying to obtain?

Thanks for the report @SMUnlimited

**Comment by SMUnlimited** [comment]
Seems to not crash with GetBaseAV2.
Just spell specific skills.

**Comment by llde** [comment]
Should be fixed with the marked commit.
I plan to release later a new version.
