### ISSUE TITLE
OnActorEquip event fires twice for enchanted clothing/armor

### ISSUE THREAD

**Issue by qwertyasdfgh2** [llde/xOBSE#92]
Tested with:

scn HandlerEquip

ref target
ref item

begin Function { target, item }
	Print $item + " equipped on " + $target
end

For enchanted apparel there's 2 prints in console, and one for other types of item.

**Comment by llde** [comment]
Thanks I wonder if it's related to the double hook in the event manager.

**Comment by llde** [comment]
Confirmed 
```
00000014    dfswd    0302B38C   Amulet of Heartheal
00000014    dfswd    0302B38C   Amulet of Heartheal
```

**Comment by llde** [comment]
@qwertyasdfgh2 Does this affect only the player?

**Comment by qwertyasdfgh2** [comment]
In the old version it was for both player and NPCs. In the latest version it seems to work correctly for both. Thanks.
