### ISSUE TITLE
GetOBSEVersion doesn't print anything

### ISSUE THREAD

**Issue by ketsuban** [llde/xOBSE#95]
According to the changelog for v21.5, `GetOBSEVersion`, `GetOBSERevision` and "Plugins detection functions" are supposed to print something to the console, but that functionality seems to have been reverted at some point. `GetOBSEVersion` is a useful diagnostic test at the console for "is OBSE installed and functioning", so it'd probably be worth readding it.

```diff
 bool Cmd_GetOBSEVersion_Execute(COMMAND_ARGS)
 {
+	if (IsConsoleMode()) Console_Print("OBSE v%d.%d", OBSE_VERSION_INTEGER, OBSE_VERSION_INTEGER_MINOR);
 	*result = OBSE_VERSION_INTEGER;

 	return true;
 }
```

**Comment by llde** [comment]
@ketsuban yes I actually forgot to add the print to that command and instead added it to IsPluginLoaded, will add
