### ISSUE TITLE
OBSE and Vampire Revolution

### ISSUE THREAD

**Issue by Lord-Calvariam** [llde/xOBSE#97]
I'm using the latest version of OBSE (22.3.1) and every time I take off my helmet and put it back on, my game crashes to the desktop.

The helmet in question is "Helmet of the Mind", which is a vanilla item that appears in random loot. Details on the helmet, if necessary are here: https://en.uesp.net/wiki/Oblivion:Generic_Magic_Apparel#Helmet_of_the_Mind

Looking at obse.log, the last error listed is for "Vampire Revolution" which can be found here: https://www.nexusmods.com/oblivion/mods/45116

Removed Vampire Revolution and the crash does not occur, however, I've been using this mod for a while now without issues.

After some testing, I determined that the cause is the version of OBSE. If I revert back to, 22.1 the issues does not occur. Using any version after this causes the crash.

Normally I wouldn't have a problem reverting back for a time but since it exists in multiple version at this point I'm not sure if you're aware of it. Also I have a different mod which requires the later version.

Unfortunately the author of Vampire Revolution hasn't updated since June 2015 so it is unlikely it will ever get updated to fix it, so I'm hoping it can be fixed on the OBSE side of things since it works fine in an older version.

Here is the log: 
[obse.log](https://github.com/llde/xOBSE/files/6604767/obse.log)

**Comment by llde** [comment]
Thanks for the report.  However the log sent report 22.1 as a version, that is xOBSE 22.1, and I can confirm that xOBSE 22.3 and 22.3.1 do report 22.3 correctly.
Post a log with xOBSE 22.3.
Also give the crash log from the Cobb Crash Logger. (install correctly also the obse debug symbols)

**Comment by Lord-Calvariam** [comment]
Ah. My apologies. Forgot to switch back to the latest version to generate the correct log.
Here it is:  [obse.log](https://github.com/llde/xOBSE/files/6605158/obse.log)

I already had the Crash Logger installed so I'll include the log here. What do you mean by "obse debug symbols"?
[CobbCrashLogger.log](https://github.com/llde/xOBSE/files/6605164/CobbCrashLogger.log)

**Comment by llde** [comment]
in the xOBSE release there is an obse.pdb file. Put in the same folder of the obse_1_2_416.dll
Remember that the pdb is linked to the version of the DLL

**Comment by Lord-Calvariam** [comment]
Ok. I put the obse.pdb file in the same folder and then caused the crash to happen again.
[CobbCrashLogger.log](https://github.com/llde/xOBSE/files/6610637/CobbCrashLogger.log)

**Comment by llde** [comment]
Umh, Vampire revoution errors are also present in the xOBSE 22.1 logs that you calimed it worked. So the issue doesn't seems the script error per se.
Maybe it's trying to print some other infos and crashing there? 

        
        0x72244A57 ==> ExpressionEvaluator::Error+0x127 in obse_1_2_416 (0x0019B0D0) 
        0x722484C3 ==> ExpressionEvaluator::Evaluate+0x713 in obse_1_2_416 (0x0019B144) 
        0x72247388 ==> ExpressionEvaluator::ExtractArgs+0x28 in obse_1_2_416 (0x0019B15C) 
        0x721E38BC ==> Cmd_ForEach_Execute+0x7C in obse_1_2_416 (0x0019B210)

**Comment by Lord-Calvariam** [comment]
I also noticed that the errors are in both logs but I thought they must have some greater significance in the later versions since it works fine in the older version.

To make sure it wasn't some kind of fluke, I spent 5 minutes in the game with the old version and took my helmet off and put it back on over 10 times and couldn't get a crash.

When using the latest version, it crashes the first time I put the helmet back on after taking it off. Tried loading the game up multiple times as well to make sure it would always crash on the first time.

**Comment by Lord-Calvariam** [comment]
Ok. After some additional testing, this is where I am at.

I found that it isn't just Helmet of the Mind. Putting on any helmet causes the game to crash.

The problem script referenced in obse.log is called VRGetCoveredFace. This reminded me of one of this mod's features where guards and other NPCs won't recognize you as a vampire if you're wearing a helmet.

To test this, I disabled that specific feature and, sure enough, the game did not crash when switching helmets.

Here is the script below. Do you see anything that appears amiss or out of place?

scn VRGetCoveredFace

;Check if the face is covered by an equipment

Ref rItem
Array_Var aIter
Short bOK

Begin _Function {}
	
	If Eval ( VRMain.abSettings["Ignore helmet"] )
		Return
	EndIf
	
	If Eval ( GetEquippedObject 0 )
		SetFunctionValue 1
		Return
	EndIf
	
	Let rItem := GetEquippedObject 1
	If ( rItem == VRMain.rLastHeadEquip )
		SetFunctionValue VRMain.bHeadEquipOK
		Return
	EndIf
		
	Let VRMain.rLastHeadEquip := rItem
	If Eval !( rItem )
		Return
	EndIf


	
	ForEach aIter <- VRMain.asItemsNames
		If Eval ( NameIncludes *aIter, rItem )
			Let bOK := 1
			Break
		EndIf
	Loop
	If ( bOK )
		Let VRMain.bHeadEquipOK := 1
		SetFunctionValue 1
		Return
	EndIf
	
	ForEach aIter <- VRMain.asItemsNames
		If Eval ( ModelPathIncludes *aIter, rItem )
			Let bOK := 1
			Break
		EndIf
	Loop

	Let VRMain.bHeadEquipOK := bOK
	SetFunctionValue bOK
	
End

**Comment by llde** [comment]
I have to ask: what do VRMain.asItemsNames contains?

**Comment by Lord-Calvariam** [comment]
My apologies but I'm not sure where to find that information.

When I open the mod in xEdit, I do see a "VRMain" under the quest tab but I don't see any reference to "asItemsNames". I also don't see any other record that begins with "VRMain".

Do you know how I could go about find that information?

Apologies for all the questions, this is the first time I've really looked this closely at a mod's files and I'm slowly crawling my way forward to understanding.

**Comment by llde** [comment]
it's supposed to be an array in the  script associated to VRMain quest.

**Comment by Lord-Calvariam** [comment]
I think I understand. The script associated with the "VRMain" quest is "VRQuestMain" and that is where I should be able to find the array.

The only reference to that array appears to be in the VR User Configuration section and it is blank.

Here is what the section looks like as a whole:

;VR user configuration
float fTokenTime		;How often tokens update?
float fChargeTime		;How fast the powers charge?
short kModifierKey		;DX key for the modifier
short kMenuKey			;DX key to open the VR menu
short kActionKey		;DX key to execute an action
short iMenuKeyMod		;Modifier mode for the VR menu key
Array_var aaPowerKey	;User power keys. Every element is a couple (DX key, modifier mode)
Array_var abSettings	;User settings. Every element is 1 if the setting is checked, 0 otherwise
Array_var afDifficult	;User difficulty. Every element is the current value/multiplier
Array_Var asItemsNames
Array_Var asItemsModels

**Comment by llde** [comment]
Array_Var asItemsNames it should be populated in some part of the script or in an external script with a link reference.
It may also be populated from a external file called with RunScriptLine

**Comment by llde** [comment]
@Lord-Calvariam  Question: Do you need to be a vampire for the crash to happen?

**Comment by Lord-Calvariam** [comment]
Yes. It only occurs when I'm a vampire.

Sorry I did try to follow your last piece of advice but I could not locate Array_Var asItemsNames in any other part of that script or a link reference or RunScriptLine anywhere though that might be my lack of experience with scripts rather then because it isn't there.

**Comment by llde** [comment]
Installed VR and I'm  getting a CTD on save load. Can debug.

**Comment by llde** [comment]
Ok I understand what's happening. The crash itself is an error inside OBSE (invalid address read), but I'm not understanding why it's invalid (maybe wrong/missing increment?). The issue came out when I changed  a value to fix some commands not being shown.
I reverted partially it for the time being, and will commit after posting this comment.
The other issue is VR. VR has a couple of calls to specific user defined functions.
One is for showing a menu.
The menu functions  should operate when called on the Player (PlayerRef.Call) or called without a reference (simple Call). 
it use GetSelf to check the reference.
Now GetSelf is a command marked with "needParent = 1". This means that  the command is supposed to be invoked with the "dot syntax" (player.GetSelf for example). Objects script  have the property to pass as the calling reference the reference the script is run on. On normal Object scripts this is the reference the script is associated. UDF scripts are Object scripts with no reference associated by default. To pass a reference to associate to the UDF you use the dot syntax with Call in the calling script, and it become the reference of the UDF.
This means that the script is calling GetSelf in a script with null reference (null thisObj to link this to the obse signatures).
Most functions that require the dot syntax just fail to execute halting the script execution for the session.  This is why I added the code to detect this situation in the Expression Evaluator.  And in fact this allowed me to discover a couple of issues in some mods.

However GetSelf is just returning 0 in this case. 
Maybe I will add later an exception for GetSelf only, as I saw that it's safe from the Oblivion code.  I'm not happy to do this. I would prefer the mod got fixed.

The worst thing is that  the reference is used for:
1) Print a debug line with the reference id.
2) If a reference is present check if it's the player,
The End.

E Porco Dio.

**Comment by llde** [comment]
@Lord-Calvariam Can you check if this DLL solve the CTD? 
https://ci.appveyor.com/api/buildjobs/ul3c71tkr8k0w7s0/artifacts/obse%2Fobse%2FRelease%201_2_0_416%2Fobse.dll
Rename it to obse_1_2_416.dll or use the obse_loader with the -altdll option

**Comment by Lord-Calvariam** [comment]
That seems to have worked. Thank you very much for looking into this.
